/**
 * Schema types for the Delegation Cloud Postgres project.
 * Generated by hand from supabase/migrations/0001–0006 until `supabase gen types`
 * can run against a linked dedicated project.
 */
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          industry: string | null;
          company_size: string | null;
          timezone: string;
          created_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["organizations"]["Row"]> & { name: string; slug: string };
        Update: Partial<Database["public"]["Tables"]["organizations"]["Row"]>;
      };
      requests: {
        Row: {
          id: string;
          organization_id: string;
          workstream_id: string | null;
          title: string;
          objective: string;
          description: string | null;
          deliverable: string | null;
          priority: string;
          status: string;
          risk_level: string;
          approval_level: string;
          due_at: string | null;
          created_by: string | null;
          assigned_operator_id: string | null;
          estimated_effort: number;
          actual_effort: number;
          automation_score: number;
          recurring: boolean;
          external_communication: boolean;
          playbook_id: string | null;
          missing_context: Json;
          customer_instructions: string;
          internal_instructions: string;
          qa_checklist: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Record<string, unknown>;
        Update: Record<string, unknown>;
      };
      invitations: {
        Row: {
          id: string;
          organization_id: string;
          email: string;
          name: string;
          role: string;
          status: string;
          invited_by: string | null;
          expires_at: string;
          accepted_at: string | null;
          created_at: string;
        };
        Insert: Record<string, unknown>;
        Update: Record<string, unknown>;
      };
    };
    Views: Record<string, never>;
    Functions: {
      my_org_ids: { Args: Record<string, never>; Returns: string[] };
      platform_role: { Args: Record<string, never>; Returns: string };
      is_platform_staff: { Args: Record<string, never>; Returns: boolean };
      is_ops_manager: { Args: Record<string, never>; Returns: boolean };
    };
    Enums: Record<string, never>;
  };
};
